tasks = [
    [[tc.SetBitrate(1, BaudRate.BaudRate9600), 5], SendLoop, WaitMode.NoWait],
    [[tc.SendBeacon(), 15], SendLoop, WaitMode.NoWait],

    [tc.ListFiles(2, '/'), Send, WaitMode.Wait],

    # Telemetry between session 160 and 161
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(100, '/telemetry.current', [i for i in range(1770, 1970, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(101, '/telemetry.current', [i for i in range(1776, 1970, 12)]), Send, WaitMode.Wait],

    # More telemetry between session 158 and 160
    [tc.DownloadFile(102, '/telemetry.current', [i for i in range(922, 1770, 50)]), Send, WaitMode.Wait],

    # Missings of high-res photo after sail deployment - High priority
    [tc.DownloadFile(87, '/sail.photo_87', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), Send, WaitMode.Wait],
    [tc.DownloadFile(88, '/sail.photo_87', [11, 12, 13, 14, 15, 16, 17, 18, 19]), Send, WaitMode.Wait],

    # Remove downloaded photos
    [tc.SendBeacon(), Send, WaitMode.Wait],
    [tc.RemoveFile(200, '/sail.photo_11'), Send, WaitMode.NoWait],
    [tc.RemoveFile(201, '/sail.photo_45'), Send, WaitMode.NoWait],
    [tc.RemoveFile(202, '/sail.photo_55'), Send, WaitMode.NoWait],
    [tc.RemoveFile(203, '/sail.photo_67'), Send, WaitMode.NoWait],
    [tc.RemoveFile(255, '/sail.photo_17'), Send, WaitMode.NoWait],
    [tc.RemoveFile(254, '/sail.photo_19'), Send, WaitMode.NoWait],

    # Missings of low-res photos just before and after sail deployment
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(13, '/sail.photo_13', [12]), Send, WaitMode.Wait],
    [tc.DownloadFile(15, '/sail.photo_15', [0, 1, 2, 3, 4, 5, 6, 7, 8]), Send, WaitMode.Wait],
    [tc.DownloadFile(16, '/sail.photo_15', [9, 10, 11, 12, 13, 14, 15]), Send, WaitMode.Wait],

    [tc.DownloadFile(21, '/sail.photo_21', [0, 1, 2, 3, 4, 5, 6, 7]), Send, WaitMode.Wait],
    [tc.DownloadFile(22, '/sail.photo_21', [8, 9, 10, 11, 12, 13, 14]), Send, WaitMode.Wait],

    [tc.DownloadFile(23, '/sail.photo_23', [32, 33, 34, 35, 18, 19, 20, 21, 22]), Send, WaitMode.Wait],
    [tc.DownloadFile(24, '/sail.photo_23', [23, 24, 25, 26, 27, 28, 29, 30, 31]), Send, WaitMode.Wait],

    [tc.DownloadFile(27, '/sail.photo_27', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), Send, WaitMode.Wait],
    [tc.DownloadFile(28, '/sail.photo_27', [10, 11, 12, 13, 14, 15, 16, 17]), Send, WaitMode.Wait],

    # Remove black photos (covered by solar panels)
    [tc.SendBeacon(), Send, WaitMode.Wait],
    [tc.RemoveFile(204, '/sail.photo_0'), Send, WaitMode.NoWait],
    [tc.RemoveFile(205, '/sail.photo_2'), Send, WaitMode.NoWait],
    [tc.RemoveFile(206, '/sail.photo_4'), Send, WaitMode.NoWait],
    [tc.RemoveFile(207, '/sail.photo_6'), Send, WaitMode.NoWait],
    [tc.RemoveFile(208, '/sail.photo_8'), Send, WaitMode.NoWait],
    [tc.RemoveFile(209, '/sail.photo_10'), Send, WaitMode.NoWait],
    [tc.RemoveFile(210, '/sail.photo_12'), Send, WaitMode.NoWait],
    [tc.RemoveFile(211, '/sail.photo_14'), Send, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.Wait],
    [tc.RemoveFile(212, '/sail.photo_16'), Send, WaitMode.NoWait],
    [tc.RemoveFile(213, '/sail.photo_18'), Send, WaitMode.NoWait],
    [tc.RemoveFile(214, '/sail.photo_20'), Send, WaitMode.NoWait],
    [tc.RemoveFile(215, '/sail.photo_22'), Send, WaitMode.NoWait],
    [tc.RemoveFile(216, '/sail.photo_24'), Send, WaitMode.NoWait],
    [tc.RemoveFile(217, '/sail.photo_26'), Send, WaitMode.NoWait],
    [tc.RemoveFile(218, '/sail.photo_28'), Send, WaitMode.NoWait],
    [tc.RemoveFile(219, '/sail.photo_30'), Send, WaitMode.NoWait],

    # Low-res photos just before and after sail deployment
    [tc.DownloadFile(29, '/sail.photo_29', [i for i in range(0, 17, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(30, '/sail.photo_29', [i for i in range(17, 33, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(31, '/sail.photo_31', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(32, '/sail.photo_31', [i for i in range(15, 29, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(33, '/sail.photo_33', [i for i in range(0, 22, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(35, '/sail.photo_35', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(37, '/sail.photo_37', [i for i in range(0, 12, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(39, '/sail.photo_39', [i for i in range(0, 21, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(41, '/sail.photo_41', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(42, '/sail.photo_41', [i for i in range(15, 32, 1)]), Send, WaitMode.Wait],

    [tc.SendBeacon(), Send, WaitMode.Wait],
    [tc.RemoveFile(220, '/sail.photo_32'), Send, WaitMode.NoWait],
    [tc.RemoveFile(221, '/sail.photo_34'), Send, WaitMode.NoWait],
    [tc.RemoveFile(222, '/sail.photo_36'), Send, WaitMode.NoWait],
    [tc.RemoveFile(223, '/sail.photo_38'), Send, WaitMode.NoWait],
    [tc.RemoveFile(224, '/sail.photo_40'), Send, WaitMode.NoWait],
    [tc.RemoveFile(225, '/sail.photo_42'), Send, WaitMode.NoWait],
    [tc.RemoveFile(226, '/sail.photo_44'), Send, WaitMode.NoWait],
    [tc.RemoveFile(227, '/sail.photo_46'), Send, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.Wait],
    [tc.RemoveFile(228, '/sail.photo_48'), Send, WaitMode.NoWait],
    [tc.RemoveFile(229, '/sail.photo_50'), Send, WaitMode.NoWait],
    [tc.RemoveFile(230, '/sail.photo_52'), Send, WaitMode.NoWait],
    [tc.RemoveFile(231, '/sail.photo_54'), Send, WaitMode.NoWait],
    [tc.RemoveFile(232, '/sail.photo_56'), Send, WaitMode.NoWait],
    [tc.RemoveFile(233, '/sail.photo_58'), Send, WaitMode.NoWait],
    [tc.RemoveFile(234, '/sail.photo_60'), Send, WaitMode.NoWait],
    [tc.RemoveFile(235, '/sail.photo_62'), Send, WaitMode.NoWait],

    # Low-res photos just before and after sail deployment
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(43, '/sail.photo_43', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(44, '/sail.photo_43', [i for i in range(15, 34, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(47, '/sail.photo_47', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(48, '/sail.photo_47', [i for i in range(15, 30, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(49, '/sail.photo_49', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(50, '/sail.photo_49', [i for i in range(15, 30, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(51, '/sail.photo_51', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(52, '/sail.photo_51', [i for i in range(15, 32, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(53, '/sail.photo_53', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(54, '/sail.photo_53', [i for i in range(15, 35, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(57, '/sail.photo_57', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(58, '/sail.photo_57', [i for i in range(15, 31, 1)]), Send, WaitMode.Wait],

    [tc.SendBeacon(), Send, WaitMode.Wait],
    [tc.RemoveFile(236, '/sail.photo_64'), Send, WaitMode.NoWait],
    [tc.RemoveFile(237, '/sail.photo_66'), Send, WaitMode.NoWait],
    [tc.RemoveFile(238, '/sail.photo_68'), Send, WaitMode.NoWait],
    [tc.RemoveFile(239, '/sail.photo_70'), Send, WaitMode.NoWait],
    [tc.RemoveFile(240, '/sail.photo_72'), Send, WaitMode.NoWait],
    [tc.RemoveFile(242, '/sail.photo_74'), Send, WaitMode.NoWait],
    [tc.RemoveFile(243, '/sail.photo_76'), Send, WaitMode.NoWait],
    [tc.RemoveFile(244, '/sail.photo_78'), Send, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.Wait],
    [tc.RemoveFile(245, '/sail.photo_80'), Send, WaitMode.NoWait],
    [tc.RemoveFile(246, '/sail.photo_82'), Send, WaitMode.NoWait],
    [tc.RemoveFile(247, '/sail.photo_84'), Send, WaitMode.NoWait],
    [tc.RemoveFile(248, '/sail.photo_86'), Send, WaitMode.NoWait],

    # Low-res photos just before and after sail deployment
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(59, '/sail.photo_59', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(60, '/sail.photo_59', [i for i in range(15, 29, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(61, '/sail.photo_61', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(62, '/sail.photo_61', [i for i in range(15, 27, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(63, '/sail.photo_63', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(64, '/sail.photo_63', [i for i in range(15, 27, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(65, '/sail.photo_65', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(66, '/sail.photo_65', [i for i in range(15, 27, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(69, '/sail.photo_69', [i for i in range(0, 22, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(71, '/sail.photo_71', [i for i in range(0, 23, 1)]), Send, WaitMode.Wait],

    # Low-res photos just before and after sail deployment
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(73, '/sail.photo_73', [i for i in range(0, 23, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(75, '/sail.photo_75', [i for i in range(0, 21, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(77, '/sail.photo_77', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(78, '/sail.photo_77', [i for i in range(15, 26, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(79, '/sail.photo_79', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(80, '/sail.photo_79', [i for i in range(15, 27, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(81, '/sail.photo_81', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(82, '/sail.photo_81', [i for i in range(15, 30, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(83, '/sail.photo_83', [i for i in range(0, 16, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(84, '/sail.photo_83', [i for i in range(16, 33, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(85, '/sail.photo_85', [i for i in range(0, 18, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(86, '/sail.photo_85', [i for i in range(18, 36, 1)]), Send, WaitMode.Wait],

    [[tc.SendBeacon(), 15], SendLoop, WaitMode.NoWait],
]