tasks = [
    [[tc.PingTelecommand(), 2], SendLoop, WaitMode.NoWait],
    [[tc.SendBeacon(), 5], SendLoop, WaitMode.NoWait],
    [[tc.SetAntennaDeployment(2, True), 2], SendLoop, WaitMode.NoWait],
    [[tc.SendBeacon(), 5], SendLoop, WaitMode.NoWait],

    [tc.DownloadFile(3, '/telemetry.leop', [i for i in range(0, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(4, '/telemetry.leop', [i for i in range(25, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(5, '/telemetry.leop', [i for i in range(12, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(6, '/telemetry.leop', [i for i in range(37, 450, 50)]), Send, WaitMode.Wait],

    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(7, '/telemetry.leop', [i for i in range(6, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(8, '/telemetry.leop', [i for i in range(18, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(9, '/telemetry.leop', [i for i in range(31, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(10, '/telemetry.leop', [i for i in range(43, 450, 50)]), Send, WaitMode.Wait],

    [tc.DownloadFile(20, '/leop', [i for i in range(0, 580, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(21, '/leop', [i for i in range(25, 580, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(22, '/leop', [i for i in range(12, 580, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(23, '/leop', [i for i in range(37, 580, 50)]), Send, WaitMode.Wait],

    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(11, '/telemetry.leop', [i for i in range(3, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(12, '/telemetry.leop', [i for i in range(9, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(13, '/telemetry.leop', [i for i in range(15, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(14, '/telemetry.leop', [i for i in range(21, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(15, '/telemetry.leop', [i for i in range(28, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(16, '/telemetry.leop', [i for i in range(34, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(17, '/telemetry.leop', [i for i in range(40, 450, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(18, '/telemetry.leop', [i for i in range(46, 450, 50)]), Send, WaitMode.Wait],
]
