tasks = [
    [[tc.SetBitrate(1, BaudRate.BaudRate9600), 5], SendLoop, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.Wait],

    [tc.ListFiles(2, '/'), Send, WaitMode.Wait],

    # Telemetry between session 118 and 121
    [tc.DownloadFile(10, '/telemetry.previous', [i for i in range(1700, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(11, '/telemetry.current', [i for i in range(0, 900, 50)]), Send, WaitMode.Wait],

    # Experiment RadFET (6th)
    [tc.PerformRadFETExperiment(20, 150, 110, 'radfet_6'), Send, WaitMode.Wait],

    # Remove photos
    [tc.SendBeacon(), Send, WaitMode.Wait],
    [tc.RemoveFile(30, '/p1_128_0'), Send, WaitMode.NoWait],
    [tc.RemoveFile(31, '/p5_128_0'), Send, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.Wait],

    [tc.ListFiles(32, '/'), Send, WaitMode.Wait],

    # More telemetry between session 118 and 121
    [tc.DownloadFile(40, '/telemetry.previous', [i for i in range(1701, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(41, '/telemetry.current', [i for i in range(1, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(42, '/telemetry.current', [i for i in range(3, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(43, '/telemetry.previous', [i for i in range(1703, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(44, '/telemetry.current', [i for i in range(5, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(45, '/telemetry.previous', [i for i in range(1705, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(46, '/telemetry.current', [i for i in range(7, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(47, '/telemetry.previous', [i for i in range(1707, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(48, '/telemetry.current', [i for i in range(9, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(49, '/telemetry.previous', [i for i in range(1709, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(50, '/telemetry.current', [i for i in range(11, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(51, '/telemetry.previous', [i for i in range(1711, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(52, '/telemetry.current', [i for i in range(13, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(53, '/telemetry.previous', [i for i in range(1713, 2280, 35)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(54, '/telemetry.current', [i for i in range(15, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(55, '/telemetry.previous', [i for i in range(1715, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(56, '/telemetry.current', [i for i in range(17, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(57, '/telemetry.previous', [i for i in range(1717, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(58, '/telemetry.current', [i for i in range(19, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(59, '/telemetry.previous', [i for i in range(1719, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(60, '/telemetry.current', [i for i in range(21, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(61, '/telemetry.previous', [i for i in range(1721, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(62, '/telemetry.current', [i for i in range(23, 900, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(63, '/telemetry.previous', [i for i in range(1723, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(64, '/telemetry.current', [i for i in range(25, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(65, '/telemetry.previous', [i for i in range(1725, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(66, '/telemetry.current', [i for i in range(27, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(67, '/telemetry.previous', [i for i in range(1727, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(68, '/telemetry.current', [i for i in range(29, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(69, '/telemetry.previous', [i for i in range(1729, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(70, '/telemetry.current', [i for i in range(31, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(71, '/telemetry.previous', [i for i in range(1731, 2280, 35)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],

    [tc.DownloadFile(72, '/telemetry.current', [i for i in range(33, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(73, '/telemetry.current', [i for i in range(35, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(74, '/telemetry.current', [i for i in range(37, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(75, '/telemetry.current', [i for i in range(39, 900, 50)]), Send, WaitMode.Wait],


    [tc.DownloadFile(76, '/telemetry.current', [i for i in range(41, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(77, '/telemetry.current', [i for i in range(43, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(78, '/telemetry.current', [i for i in range(45, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(79, '/telemetry.current', [i for i in range(47, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(80, '/telemetry.current', [i for i in range(49, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(81, '/telemetry.current', [i for i in range(51, 900, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],


    # Even more telemetry between session 118 and 121
    [tc.DownloadFile(82, '/telemetry.previous', [i for i in range(1702, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(83, '/telemetry.previous', [i for i in range(1704, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(84, '/telemetry.previous', [i for i in range(1706, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(85, '/telemetry.previous', [i for i in range(1708, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(86, '/telemetry.previous', [i for i in range(1710, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(87, '/telemetry.previous', [i for i in range(1712, 2280, 35)]), Send, WaitMode.Wait],

    [tc.DownloadFile(88, '/telemetry.current', [i for i in range(2, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(89, '/telemetry.current', [i for i in range(4, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(90, '/telemetry.current', [i for i in range(6, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(91, '/telemetry.current', [i for i in range(8, 900, 50)]), Send, WaitMode.Wait],

    [tc.DownloadFile(92, '/telemetry.previous', [i for i in range(1714, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(93, '/telemetry.previous', [i for i in range(1716, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(94, '/telemetry.previous', [i for i in range(1718, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(95, '/telemetry.previous', [i for i in range(1720, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(96, '/telemetry.previous', [i for i in range(1722, 2280, 35)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],

    [tc.DownloadFile(97, '/telemetry.current', [i for i in range(10, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(98, '/telemetry.current', [i for i in range(12, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(99, '/telemetry.current', [i for i in range(14, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(100, '/telemetry.current', [i for i in range(16, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(101, '/telemetry.current', [i for i in range(18, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(102, '/telemetry.current', [i for i in range(20, 900, 50)]), Send, WaitMode.Wait],

    [tc.DownloadFile(103, '/telemetry.previous', [i for i in range(1724, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(104, '/telemetry.previous', [i for i in range(1726, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(105, '/telemetry.previous', [i for i in range(1728, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(106, '/telemetry.previous', [i for i in range(1730, 2280, 35)]), Send, WaitMode.Wait],
    [tc.DownloadFile(107, '/telemetry.previous', [i for i in range(1732, 2280, 35)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],

    [tc.DownloadFile(108, '/telemetry.current', [i for i in range(22, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(109, '/telemetry.current', [i for i in range(24, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(110, '/telemetry.current', [i for i in range(26, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(111, '/telemetry.current', [i for i in range(28, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(112, '/telemetry.current', [i for i in range(30, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(113, '/telemetry.current', [i for i in range(32, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(114, '/telemetry.current', [i for i in range(34, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(115, '/telemetry.current', [i for i in range(36, 900, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(116, '/telemetry.current', [i for i in range(38, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(117, '/telemetry.current', [i for i in range(40, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(118, '/telemetry.current', [i for i in range(42, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(119, '/telemetry.current', [i for i in range(44, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(120, '/telemetry.current', [i for i in range(46, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(121, '/telemetry.current', [i for i in range(48, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(122, '/telemetry.current', [i for i in range(50, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(123, '/telemetry.current', [i for i in range(52, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(124, '/telemetry.current', [i for i in range(54, 900, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(125, '/telemetry.current', [i for i in range(56, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(126, '/telemetry.current', [i for i in range(58, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(127, '/telemetry.current', [i for i in range(60, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(128, '/telemetry.current', [i for i in range(62, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(129, '/telemetry.current', [i for i in range(64, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(130, '/telemetry.current', [i for i in range(66, 900, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(131, '/telemetry.current', [i for i in range(68, 900, 50)]), Send, WaitMode.Wait],

    [tc.SendBeacon(), Send, WaitMode.Wait],
]