tasks = [
    [[tc.SetBitrate(1, BaudRate.BaudRate9600), 5], SendLoop, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.Wait],

    [tc.ListFiles(2, '/'), Send, WaitMode.Wait],

    # Telemetry between session 115 and 116
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(10, '/telemetry.current', [i for i in range(500, 700, 10)]), Send, WaitMode.Wait],
    [tc.DownloadFile(11, '/telemetry.current', [i for i in range(505, 700, 10)]), Send, WaitMode.Wait],

    # More telemetry between session 115 and 116
    [tc.DownloadFile(12, '/telemetry.current', [i for i in range(501, 700, 10)]), Send, WaitMode.Wait],
    [tc.DownloadFile(13, '/telemetry.current', [i for i in range(502, 700, 10)]), Send, WaitMode.Wait],
    [tc.DownloadFile(14, '/telemetry.current', [i for i in range(503, 700, 10)]), Send, WaitMode.Wait],
    [tc.DownloadFile(15, '/telemetry.current', [i for i in range(504, 700, 10)]), Send, WaitMode.Wait],
    [tc.DownloadFile(16, '/telemetry.current', [i for i in range(506, 700, 10)]), Send, WaitMode.Wait],
    [tc.DownloadFile(17, '/telemetry.current', [i for i in range(507, 700, 10)]), Send, WaitMode.Wait],
    [tc.DownloadFile(18, '/telemetry.current', [i for i in range(508, 700, 10)]), Send, WaitMode.Wait],
    [tc.DownloadFile(19, '/telemetry.current', [i for i in range(509, 700, 10)]), Send, WaitMode.Wait],

    # Download suns exp 7 primary file
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(30, '/suns_7', [i for i in range(0, 20, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(31, '/suns_7', [i for i in range(20, 40, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(32, '/suns_7', [i for i in range(40, 60, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(33, '/suns_7', [i for i in range(60, 80, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(34, '/suns_7', [i for i in range(80, 100, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(35, '/suns_7', [i for i in range(100, 120, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(36, '/suns_7', [i for i in range(120, 140, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(37, '/suns_7', [i for i in range(140, 160, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(38, '/suns_7', [i for i in range(160, 180, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(39, '/suns_7', [i for i in range(180, 200, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(40, '/suns_7', [i for i in range(200, 220, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(41, '/suns_7', [i for i in range(220, 240, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(42, '/suns_7', [i for i in range(240, 260, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(43, '/suns_7', [i for i in range(260, 280, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(44, '/suns_7', [i for i in range(280, 300, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(45, '/suns_7', [i for i in range(300, 320, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(46, '/suns_7', [i for i in range(320, 340, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(47, '/suns_7', [i for i in range(340, 360, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(48, '/suns_7', [i for i in range(360, 380, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(49, '/suns_7', [i for i in range(380, 400, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(50, '/suns_7', [i for i in range(400, 420, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(51, '/suns_7', [i for i in range(420, 440, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(52, '/suns_7', [i for i in range(440, 460, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(53, '/suns_7', [i for i in range(460, 480, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(54, '/suns_7', [i for i in range(480, 500, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(55, '/suns_7', [i for i in range(500, 520, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(56, '/suns_7', [i for i in range(520, 540, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(57, '/suns_7', [i for i in range(540, 560, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(58, '/suns_7', [i for i in range(560, 580, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(59, '/suns_7', [i for i in range(580, 593, 1)]), Send, WaitMode.Wait],

    # Download suns exp 7 secondary file
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(60, '/suns_7_sec', [i for i in range(0, 20, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(61, '/suns_7_sec', [i for i in range(20, 40, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(62, '/suns_7_sec', [i for i in range(40, 60, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(63, '/suns_7_sec', [i for i in range(60, 80, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(64, '/suns_7_sec', [i for i in range(80, 100, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(65, '/suns_7_sec', [i for i in range(100, 120, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(66, '/suns_7_sec', [i for i in range(120, 140, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(67, '/suns_7_sec', [i for i in range(140, 160, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(68, '/suns_7_sec', [i for i in range(160, 180, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(69, '/suns_7_sec', [i for i in range(180, 200, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(70, '/suns_7_sec', [i for i in range(200, 220, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(71, '/suns_7_sec', [i for i in range(220, 240, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(72, '/suns_7_sec', [i for i in range(240, 260, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(73, '/suns_7_sec', [i for i in range(260, 280, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(74, '/suns_7_sec', [i for i in range(280, 297, 1)]), Send, WaitMode.Wait],

    [tc.SendBeacon(), Send, WaitMode.Wait],
]