tasks = [
    [[tc.SetBitrate(1, BaudRate.BaudRate9600), 5], SendLoop, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.Wait],

    [tc.ListFiles(2, '/'), Send, WaitMode.Wait],

    # Telemetry between session 99 and 100
    [tc.DownloadFile(10, '/telemetry.current', [i for i in range(630, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(11, '/telemetry.current', [i for i in range(636, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(12, '/telemetry.current', [i for i in range(633, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(13, '/telemetry.current', [i for i in range(639, 830, 12)]), Send, WaitMode.Wait],

    # More telemetry during suns exp
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(20, '/telemetry.current', [i for i in range(631, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(21, '/telemetry.current', [i for i in range(632, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(22, '/telemetry.current', [i for i in range(634, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(23, '/telemetry.current', [i for i in range(635, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(24, '/telemetry.current', [i for i in range(637, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(25, '/telemetry.current', [i for i in range(638, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(26, '/telemetry.current', [i for i in range(640, 830, 12)]), Send, WaitMode.Wait],
    [tc.DownloadFile(27, '/telemetry.current', [i for i in range(641, 830, 12)]), Send, WaitMode.Wait],

    # Download suns exp 6 primary file
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(30, '/suns_6', [i for i in range(0, 20, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(31, '/suns_6', [i for i in range(20, 40, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(32, '/suns_6', [i for i in range(40, 60, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(33, '/suns_6', [i for i in range(60, 80, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(34, '/suns_6', [i for i in range(80, 100, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(35, '/suns_6', [i for i in range(100, 120, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(36, '/suns_6', [i for i in range(120, 140, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(37, '/suns_6', [i for i in range(140, 160, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(38, '/suns_6', [i for i in range(160, 180, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(39, '/suns_6', [i for i in range(180, 200, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(40, '/suns_6', [i for i in range(200, 220, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(41, '/suns_6', [i for i in range(220, 240, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(42, '/suns_6', [i for i in range(240, 260, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(43, '/suns_6', [i for i in range(260, 280, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(44, '/suns_6', [i for i in range(280, 300, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(45, '/suns_6', [i for i in range(300, 320, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(46, '/suns_6', [i for i in range(320, 340, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(47, '/suns_6', [i for i in range(340, 360, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(48, '/suns_6', [i for i in range(360, 380, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(49, '/suns_6', [i for i in range(380, 400, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(50, '/suns_6', [i for i in range(400, 420, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(51, '/suns_6', [i for i in range(420, 440, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(52, '/suns_6', [i for i in range(440, 460, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(53, '/suns_6', [i for i in range(460, 480, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(54, '/suns_6', [i for i in range(480, 500, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(55, '/suns_6', [i for i in range(500, 520, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(56, '/suns_6', [i for i in range(520, 540, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(57, '/suns_6', [i for i in range(540, 560, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(58, '/suns_6', [i for i in range(560, 575, 1)]), Send, WaitMode.Wait],

    # Download suns exp 6 secondary file
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(60, '/suns_6_sec', [i for i in range(0, 20, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(61, '/suns_6_sec', [i for i in range(20, 40, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(62, '/suns_6_sec', [i for i in range(40, 60, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(63, '/suns_6_sec', [i for i in range(60, 80, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(64, '/suns_6_sec', [i for i in range(80, 100, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(65, '/suns_6_sec', [i for i in range(100, 120, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(66, '/suns_6_sec', [i for i in range(120, 140, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(67, '/suns_6_sec', [i for i in range(140, 160, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(68, '/suns_6_sec', [i for i in range(160, 180, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(69, '/suns_6_sec', [i for i in range(180, 200, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(70, '/suns_6_sec', [i for i in range(200, 220, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(71, '/suns_6_sec', [i for i in range(220, 240, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(72, '/suns_6_sec', [i for i in range(240, 260, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(73, '/suns_6_sec', [i for i in range(260, 280, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(74, '/suns_6_sec', [i for i in range(280, 300, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(75, '/suns_6_sec', [i for i in range(300, 322, 1)]), Send, WaitMode.Wait],

    [[tc.SendBeacon(), 20], SendLoop, WaitMode.NoWait],
]
