tasks = [
    [[tc.SetBitrate(1, BaudRate.BaudRate9600), 5], SendLoop, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.Wait],

    [tc.ListFiles(2, '/'), Send, WaitMode.Wait],

    # Telemetry between session 106 and 107
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(10, '/telemetry.current', [i for i in range(0, 400, 25)]), Send, WaitMode.Wait],
    [tc.DownloadFile(11, '/telemetry.current', [i for i in range(12, 400, 25)]), Send, WaitMode.Wait],
    [tc.DownloadFile(12, '/telemetry.previous', [i for i in range(1100, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(13, '/telemetry.previous', [i for i in range(1125, 2280, 50)]), Send, WaitMode.Wait],
    
    # Seventh SunS experiment
    [tc.PerformSunSExperiment(20, 0, 20, 254, datetime.timedelta(seconds=2), 7, datetime.timedelta(seconds=10), 'suns_7'), Send, WaitMode.Wait],

    # More telemetry between session 106 and 107
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(30, '/telemetry.current', [i for i in range(6, 400, 25)]), Send, WaitMode.Wait],
    [tc.DownloadFile(31, '/telemetry.current', [i for i in range(18, 400, 25)]), Send, WaitMode.Wait],
    [tc.DownloadFile(32, '/telemetry.previous', [i for i in range(1112, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(33, '/telemetry.previous', [i for i in range(1137, 2280, 50)]), Send, WaitMode.Wait],

    [tc.DownloadFile(34, '/telemetry.current', [i for i in range(3, 400, 25)]), Send, WaitMode.Wait],
    [tc.DownloadFile(35, '/telemetry.current', [i for i in range(9, 400, 25)]), Send, WaitMode.Wait],
    [tc.DownloadFile(36, '/telemetry.current', [i for i in range(15, 400, 25)]), Send, WaitMode.Wait],
    [tc.DownloadFile(37, '/telemetry.current', [i for i in range(21, 400, 25)]), Send, WaitMode.Wait],

    [tc.DownloadFile(38, '/telemetry.previous', [i for i in range(1106, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(39, '/telemetry.previous', [i for i in range(1118, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(40, '/telemetry.previous', [i for i in range(1131, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(41, '/telemetry.previous', [i for i in range(1143, 2280, 50)]), Send, WaitMode.Wait],

    # Much more telemetry between session 106 and 107
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(42, '/telemetry.previous', [i for i in range(1103, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(43, '/telemetry.previous', [i for i in range(1109, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(44, '/telemetry.previous', [i for i in range(1115, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(45, '/telemetry.previous', [i for i in range(1121, 2280, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(46, '/telemetry.previous', [i for i in range(1128, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(47, '/telemetry.previous', [i for i in range(1134, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(48, '/telemetry.previous', [i for i in range(1140, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(49, '/telemetry.previous', [i for i in range(1146, 2280, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(60, '/telemetry.current', [i for i in range(1, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(61, '/telemetry.current', [i for i in range(2, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(62, '/telemetry.current', [i for i in range(4, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(63, '/telemetry.current', [i for i in range(5, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(64, '/telemetry.current', [i for i in range(7, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(65, '/telemetry.current', [i for i in range(8, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(66, '/telemetry.current', [i for i in range(10, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(67, '/telemetry.current', [i for i in range(11, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(68, '/telemetry.current', [i for i in range(13, 400, 15)]), Send, WaitMode.Wait],
    [tc.DownloadFile(69, '/telemetry.current', [i for i in range(14, 400, 15)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(70, '/telemetry.previous', [i for i in range(1101, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(71, '/telemetry.previous', [i for i in range(1102, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(72, '/telemetry.previous', [i for i in range(1104, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(73, '/telemetry.previous', [i for i in range(1105, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(74, '/telemetry.previous', [i for i in range(1107, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(75, '/telemetry.previous', [i for i in range(1108, 2280, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(76, '/telemetry.previous', [i for i in range(1110, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(77, '/telemetry.previous', [i for i in range(1111, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(78, '/telemetry.previous', [i for i in range(1113, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(79, '/telemetry.previous', [i for i in range(1114, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(80, '/telemetry.previous', [i for i in range(1116, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(81, '/telemetry.previous', [i for i in range(1117, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(82, '/telemetry.previous', [i for i in range(1119, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(83, '/telemetry.previous', [i for i in range(1120, 2280, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(84, '/telemetry.previous', [i for i in range(1122, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(85, '/telemetry.previous', [i for i in range(1123, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(86, '/telemetry.previous', [i for i in range(1124, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(87, '/telemetry.previous', [i for i in range(1126, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(88, '/telemetry.previous', [i for i in range(1127, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(89, '/telemetry.previous', [i for i in range(1129, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(90, '/telemetry.previous', [i for i in range(1130, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(91, '/telemetry.previous', [i for i in range(1132, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(92, '/telemetry.previous', [i for i in range(1133, 2280, 50)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(93, '/telemetry.previous', [i for i in range(1135, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(94, '/telemetry.previous', [i for i in range(1137, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(95, '/telemetry.previous', [i for i in range(1138, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(96, '/telemetry.previous', [i for i in range(1139, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(97, '/telemetry.previous', [i for i in range(1141, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(98, '/telemetry.previous', [i for i in range(1144, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(99, '/telemetry.previous', [i for i in range(1145, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(100, '/telemetry.previous', [i for i in range(1147, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(101, '/telemetry.previous', [i for i in range(1148, 2280, 50)]), Send, WaitMode.Wait],
    [tc.DownloadFile(102, '/telemetry.previous', [i for i in range(1149, 2280, 50)]), Send, WaitMode.Wait],

    [tc.SendBeacon(), Send, WaitMode.Wait],
]