tasks = [
    [[tc.SetBitrate(1, BaudRate.BaudRate1200), 5], SendLoop, WaitMode.NoWait],
    [[tc.SendBeacon(), 15], SendLoop, WaitMode.NoWait],

    [tc.ListFiles(2, '/'), Send, WaitMode.Wait],

    # STOP sail deployment by OBC
    [tc.StopSailDeployment(3), Send, WaitMode.Wait],

    # Telemetry between session 158 and 160 - to estimate lifetime based on battery voltage
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(100, '/telemetry.current', [i for i in range(910, 1900, 100)]), Send, WaitMode.Wait],
    [tc.DownloadFile(101, '/telemetry.current', [i for i in range(960, 1900, 100)]), Send, WaitMode.Wait],

    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(102, '/telemetry.current', [i for i in range(935, 1900, 100)]), Send, WaitMode.Wait],
    [tc.DownloadFile(103, '/telemetry.current', [i for i in range(985, 1900, 100)]), Send, WaitMode.Wait],

    # Missings of low-res Sail exp photos (after sail deployment)
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(67, '/sail.photo_67', [18]), Send, WaitMode.Wait], # VERY IMPORTANT !!!!

    [tc.DownloadFile(45, '/sail.photo_45', [i for i in range(25, 29, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(55, '/sail.photo_55', [i for i in range(25, 32, 1)]), Send, WaitMode.Wait],

    # Missing sail.exp chunk
    [tc.DownloadFile(199, '/sail.exp', [21]), Send, WaitMode.Wait],

    # More telemetry between session 158 and 160
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(104, '/telemetry.current', [i for i in range(922, 1900, 100)]), Send, WaitMode.Wait],
    [tc.DownloadFile(105, '/telemetry.current', [i for i in range(947, 1900, 100)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(106, '/telemetry.current', [i for i in range(972, 1900, 100)]), Send, WaitMode.Wait],
    [tc.DownloadFile(107, '/telemetry.current', [i for i in range(997, 1900, 100)]), Send, WaitMode.Wait],

    # High-res photo after sail deployment
    [tc.DownloadFile(87, '/sail.photo_87', [i for i in range(0, 20, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(88, '/sail.photo_87', [i for i in range(20, 40, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(89, '/sail.photo_87', [i for i in range(40, 60, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(90, '/sail.photo_87', [i for i in range(60, 80, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(91, '/sail.photo_87', [i for i in range(80, 100, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(92, '/sail.photo_87', [i for i in range(100, 114, 1)]), Send, WaitMode.Wait],

    # Low-res photos just before and after sail deployment
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(11, '/sail.photo_11', [i for i in range(0, 8, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(13, '/sail.photo_13', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(14, '/sail.photo_13', [i for i in range(15, 29, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(15, '/sail.photo_15', [i for i in range(0, 16, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(16, '/sail.photo_15', [i for i in range(16, 33, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(17, '/sail.photo_17', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(18, '/sail.photo_17', [i for i in range(15, 29, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(19, '/sail.photo_19', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(20, '/sail.photo_19', [i for i in range(15, 33, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(21, '/sail.photo_21', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(22, '/sail.photo_21', [i for i in range(15, 34, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(23, '/sail.photo_23', [i for i in range(0, 18, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(24, '/sail.photo_23', [i for i in range(18, 36, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(25, '/sail.photo_25', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(26, '/sail.photo_25', [i for i in range(15, 34, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(27, '/sail.photo_27', [i for i in range(0, 17, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(28, '/sail.photo_27', [i for i in range(17, 34, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(29, '/sail.photo_29', [i for i in range(0, 17, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(30, '/sail.photo_29', [i for i in range(17, 33, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(31, '/sail.photo_31', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(32, '/sail.photo_31', [i for i in range(15, 29, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(33, '/sail.photo_33', [i for i in range(0, 22, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(35, '/sail.photo_35', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(37, '/sail.photo_37', [i for i in range(0, 12, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(39, '/sail.photo_39', [i for i in range(0, 21, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(41, '/sail.photo_41', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(42, '/sail.photo_41', [i for i in range(15, 32, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(43, '/sail.photo_43', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(44, '/sail.photo_43', [i for i in range(15, 34, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(47, '/sail.photo_47', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(48, '/sail.photo_47', [i for i in range(15, 30, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(49, '/sail.photo_49', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(50, '/sail.photo_49', [i for i in range(15, 30, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(51, '/sail.photo_51', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(52, '/sail.photo_51', [i for i in range(15, 32, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(53, '/sail.photo_53', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(54, '/sail.photo_53', [i for i in range(15, 35, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(57, '/sail.photo_57', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(58, '/sail.photo_57', [i for i in range(15, 31, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(59, '/sail.photo_59', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(60, '/sail.photo_59', [i for i in range(15, 29, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(61, '/sail.photo_61', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(62, '/sail.photo_61', [i for i in range(15, 27, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(63, '/sail.photo_63', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(64, '/sail.photo_63', [i for i in range(15, 27, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(65, '/sail.photo_65', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(66, '/sail.photo_65', [i for i in range(15, 27, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(69, '/sail.photo_69', [i for i in range(0, 22, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(71, '/sail.photo_71', [i for i in range(0, 23, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(73, '/sail.photo_73', [i for i in range(0, 23, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(75, '/sail.photo_75', [i for i in range(0, 21, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(77, '/sail.photo_77', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(78, '/sail.photo_77', [i for i in range(15, 26, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(79, '/sail.photo_79', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(80, '/sail.photo_79', [i for i in range(15, 27, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(81, '/sail.photo_81', [i for i in range(0, 15, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(82, '/sail.photo_81', [i for i in range(15, 30, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(83, '/sail.photo_83', [i for i in range(0, 16, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(84, '/sail.photo_83', [i for i in range(16, 33, 1)]), Send, WaitMode.Wait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.DownloadFile(85, '/sail.photo_85', [i for i in range(0, 18, 1)]), Send, WaitMode.Wait],
    [tc.DownloadFile(86, '/sail.photo_85', [i for i in range(18, 36, 1)]), Send, WaitMode.Wait],

    [[tc.SendBeacon(), 15], SendLoop, WaitMode.NoWait],
]